### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by zolbooo** [zolbooo/powerhusky#1]
## TODO

1. Webhook
   - [x] GCE setup
   - [x] Server setup (via autodiscovery of IP using GCE API)
   - [x] VPS enabling
   - [x] GitLab integration
2. Daemon
   - [x] Webhook-daemon communication
   - [x] Power-off logic
3. Security
   - [x] Mutual authorization
4. Refactorings
   - [x] Webhook configuration
5. Testing
   - [x] GitLab integration
   - [x] Webhook authentication
   - [x] Daemon job counter
   - [x] Daemon authentication
6. Deployment
   - [x] Github Action releases on tags
   - [x] Auto-deploy webhook
